/*******************************************************************************
 * Copyright (c) 2002-2006 Innoopract Informationssysteme GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Innoopract Informationssysteme GmbH - initial API and implementation
 ******************************************************************************/
package com.w4t.webcardlayoutkit;

import com.w4t.Renderer;
import com.w4t.WebCardLayout;
import com.w4t.util.RendererCache;
import com.w4t.util.browser.Default;

/** <p>Tests the rendering of com.w4t.WebCardLayout with a default no-script
 * browser.</p>
  */
public class WebCardLayoutRenderer_Default_Noscript_Test
  extends WebCardLayoutRendererBase
{

  public WebCardLayoutRenderer_Default_Noscript_Test( final String name ) {
    super( name );
    setGenerateResources( false );
  }
  
  public void testRenderingKit() {
    RendererCache rendererCache = RendererCache.getInstance();
    Renderer renderer = rendererCache.retrieveRenderer( WebCardLayout.class, 
                                                        browser );
    assertEquals( WebCardLayoutRenderer_Default_Noscript.class, 
                  renderer.getClass() );
  }
  
  public void testRender() throws Exception {
    runRenderTest();
  }
  
  protected void setUp() throws Exception {
    super.setUp();
    offset = 100;
    browser = new Default( false );
  }
}
//$endOfPublicClass
class Render_100_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_105_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_110_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_109 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep55\" border=\"0\"></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep56\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep57\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep58\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_108 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "bottom",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep51\" border=\"0\"></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep52\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep53\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep54\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_107 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "middle",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep47\" border=\"0\"></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep48\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep49\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep50\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_106 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep43\" border=\"0\"></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep44\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep45\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-right:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep46\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_105 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "right",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td width=\"100%\" style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep39\" border=\"0\"></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep40\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep41\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep42\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_102_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_104 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td width=\"50%\" style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep35\" border=\"0\"></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep36\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep37\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep38\" border=\"0\"></td></tr></table></td><td width=\"50%\" style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_103 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-bottom:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep31\" border=\"0\"></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep32\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep33\" border=\"0\"></td></tr></table></td><td style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep34\" border=\"0\"></td></tr></table></td><td width=\"100%\" style=\"border-top:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_102 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "right",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td width=\"100%\" style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep27\" border=\"0\"></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep28\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep29\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep30\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_101 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td width=\"50%\" style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep23\" border=\"0\"></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep24\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep25\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep26\" border=\"0\"></td></tr></table></td><td width=\"50%\" style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_107_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_100 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-left:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep19\" border=\"0\"></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep20\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep21\" border=\"0\"></td></tr></table></td><td style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep22\" border=\"0\"></td></tr></table></td><td width=\"100%\" style=\"border-bottom:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;</td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_104_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_109_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_101_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_111 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "bottom",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep63\" border=\"0\"></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep64\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep65\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep66\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_110 {

  private static String[] res = new String[] {
    "<",
    "table",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "id",
    "=\"",
    "p2",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    " ",
    "align",
    "=\"",
    "center",
    "\"",
    " ",
    "valign",
    "=\"",
    "top",
    "\"",
    " ",
    "bgcolor",
    "=\"",
    "#ffffff",
    "\"",
    " ",
    "style",
    "=\"",
    "font-family:arial,verdana;font-size:8pt;",
    "\"",
    ">",
    "",
    "<",
    "table",
    " ",
    "id",
    "=\"",
    "p3",
    "\"",
    " ",
    "width",
    "=\"",
    "100%",
    "\"",
    " ",
    "cellspacing",
    "=\"",
    "0",
    "\"",
    " ",
    "cellpadding",
    "=\"",
    "0",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "Label1",
    "</",
    "span",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "submit",
    "\"",
    " ",
    "name",
    "=\"",
    "p5",
    "\"",
    " ",
    "value",
    "=\"",
    "Button1",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsscd1f6403",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "text",
    "\"",
    " ",
    "name",
    "=\"",
    "p6",
    "\"",
    " ",
    "value",
    "=\"",
    "",
    "\"",
    " ",
    "id",
    "=\"",
    "p6",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssfae83ad",
    "\"",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "<",
    "tr",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "<",
    "td",
    ">",
    "",
    "&nbsp;",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">",
    "",
    "</",
    "td",
    ">",
    "<",
    "td",
    " ",
    "valign",
    "=\"",
    "middle",
    "\"",
    ">",
    "",
    "<table cellspacing=\"0\" cellpadding=\"1\" border=\"0\"><tr><td nowrap bgcolor=\"#ffffff\" style=\"font-family:arial,verdana;font-size:8pt;border-top:solid 1px #ff9900;border-bottom:solid 1px #ff9900;border-right:solid 1px #ff9900;\">&nbsp;<span class=\"w4tCss1a931d40\">Card1</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep59\" border=\"0\"></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card2</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep60\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card3</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep61\" border=\"0\"></td></tr></table></td></tr><tr><td style=\"border-left:1px solid #ff9900\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\"><tr><td nowrap bgcolor=\"#e6e3e6\" style=\"font-family:arial,verdana;font-size:8pt;\">&nbsp;<span class=\"w4tCss4b203ae7\">Card4</span>&nbsp;<input type=\"image\" src=\"resources/images/submitter.gif\" name=\"waep62\" border=\"0\"></td></tr></table></td></tr></table>",
    "</",
    "td",
    ">",
    "</",
    "tr",
    ">",
    "</",
    "table",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_106_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_111_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_103_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_108_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsscd1f6403, font-family:arial,verdana;font-size:8pt; ]",
    "com.w4t.types.CssClass [ .w4tCss1a931d40, font-family:arial,verdana;font-size:8pt;font-weight:bold;color:#000000;text-decoration:none;line-height:20px; ]",
    "com.w4t.types.CssClass [ .w4tCssfae83ad, font-family:arial,verdana;font-size:8pt;width:90; ]",
    "com.w4t.types.CssClass [ .w4tCss4b203ae7, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none; ]"
  };

  static String[] getRes() {
    return res;
  }
}

