/*******************************************************************************
 * Copyright (c) 2002-2006 Innoopract Informationssysteme GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Innoopract Informationssysteme GmbH - initial API and implementation
 ******************************************************************************/
package com.w4t.dhtml.treeviewkit;

import java.io.File;

import org.eclipse.rwt.internal.IInitialization;
import org.eclipse.rwt.internal.browser.Ie5up;

import com.w4t.*;
import com.w4t.dhtml.*;
import com.w4t.dhtml.event.DragDropEvent;
import com.w4t.dhtml.event.DragDropListener;
import com.w4t.event.WebActionEvent;
import com.w4t.event.WebActionListener;
import com.w4t.util.image.ImageCache;

/** <p>Tests the rendering for org.eclipse.rap.dhtml.TreeView (and thus for
 * TreeNode and TreeLeaf as well) for Navigator 6up.</p>
 */
public class TreeViewRenderer_Ie5up_NoScript_Test extends RenderingTestCase {
  
  public TreeViewRenderer_Ie5up_NoScript_Test( final String name ) {
    super( name );
    setGenerateResources( false );
  }
  
  protected void setUp() throws Exception {
    super.setUp();
    W4TFixture.setPrivateField( ImageCache.class, null, "_instance", null );
    ImageCache.createInstance( W4TFixture.getWebAppBase().toString(), 
                               IInitialization.NOSCRIPT_SUBMITTERS_USE );
    String img1Name = "resources/images/generated/82f7c683860a85c182.gif";
    File img1 = new File( W4TFixture.getWebAppBase(), img1Name );
    W4TFixture.copyTestResource( img1Name, img1 );
    String img2Name = "resources/images/generated/a2fb9a01c602ae.gif";
    File img2 = new File( W4TFixture.getWebAppBase(), img2Name );
    W4TFixture.copyTestResource( img2Name, img2 );
    String img3Name = "resources/images/generated/b0f7e8cebcdea2bd.gif";
    File img3 = new File( W4TFixture.getWebAppBase(), img3Name );
    W4TFixture.copyTestResource( img3Name, img3 );
    String img4Name = "resources/images/generated/bcd0970bc68fbca0.gif";
    File img4 = new File( W4TFixture.getWebAppBase(), img4Name );
    W4TFixture.copyTestResource( img4Name, img4 );
    String img5Name = "resources/images/generated/dff8c3a4e2b4c79080.gif";
    File img5 = new File( W4TFixture.getWebAppBase(), img5Name );
    W4TFixture.copyTestResource( img5Name, img5 );
  }
  public void tearDown() throws Exception {
    super.tearDown();
    W4TFixture.setPrivateField( ImageCache.class, null, "_instance", null );
  }
   
   // testing methods
   //////////////////

   public void testRender() throws Exception {
     // reset the component counter, so that we have always the same IDs
     resetWebComponentCounter();
     // needed 
     WebForm testForm = new WebForm() {    
       protected void setWebComponents() throws Exception {      
       }
     };
     
     TreeView tv = new TreeView();
     testForm.add( tv, WebBorderLayout.CENTER );
     
     // node without children
     TreeNode tn1 = new TreeNode();
     tn1.setLabel( "TreeNode 1" );
//     tn1.addWebActionListener( new WebActionListener() {
//      public void webActionPerformed( WebActionEvent e ) {
//      }
//       
//     });
     tv.addItem( tn1 );
     
     // node with child nodes
     TreeNode tn2 = new TreeNode();
     tn2.setLabel( "TreeNode 2" );
     tv.addItem( tn2 );

     TreeNode tn2_1 = new TreeNode();
     tn2_1.setLabel( "TreeNode 2_1" );
     tn2.addItem( tn2_1 );
     tn2.addWebActionListener( new WebActionListener() {
       public void webActionPerformed( final WebActionEvent e ) {
       }
     });

     TreeNode tn2_1_1 = new TreeNode();
     tn2_1_1.setLabel( "TreeNode 2_1_1" );
     tn2_1.addItem( tn2_1_1 );

     TreeNode tn2_1_2 = new TreeNode();
     tn2_1_2.setLabel( "TreeNode 2_1_2" );
     tn2_1.addItem( tn2_1_2 );

     TreeLeaf tl2_1_3 = new TreeLeaf();
     tl2_1_3.setLabel( "TreeLeaf 2_1_3" );
     tn2_1.addItem( tl2_1_3 );

     TreeNode tn2_2 = new TreeNode();
     tn2_2.setLabel( "TreeNode 2_2" );
     tn2.addItem( tn2_2 );

     // node with child node and leaf
     TreeNode tn3 = new TreeNode();
     tn3.setLabel( "TreeNode 3" );
     tv.addItem( tn3 );

     TreeNode tn3_1 = new TreeNode();
     tn3_1.setLabel( "TreeNode 3_1" );
     tn3.addItem( tn3_1 );

     TreeLeaf tl3_2 = new TreeLeaf();
     tl3_2.setLabel( "TreeLeaf 3_2" );
     tn3.addItem( tl3_2 );
     
     // needed for renderer loading    
     W4TFixture.fakeBrowser( new Ie5up( false, false ) );


     // perform actual tests
     ///////////////////////
     doRenderTest( tv, 50 );
     
     // set a single node expanded 
     tn3.setExpanded( true );
     doRenderTest( tv, 51 );

     // change image set
     tv.setImageSetName( "resources/images/treeview/swing/Swing" );
     doRenderTest( tv, 52 );
     
     // change back the image set of a single node
     tn2_1.setImageSetName( "resources/images/treeview/modern/Modern" );
     doRenderTest( tv, 53 );
     // add webActionEventListener for tree leaf
     tv.addWebActionListener( new WebActionListener() {
       public void webActionPerformed( WebActionEvent e ) {
         // do nothing
       }
     });
     doRenderTest( tv, 54 );
     // add dragDropListener
     tv.addDragDropListener( new DragDropListener() {
       public void receivedDragDrop( DragDropEvent evt ) {
         // do nothing
       }
     } );
     doRenderTest( tv, 55 );
   }
}
//$endOfPublicClass
class Render_54 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep3",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/bcd0970bc68fbca0.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep3",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 1",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tncp10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Collapse",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/a2fb9a01c602ae.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 3",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep11",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/b0f7e8cebcdea2bd.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep11",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 3_1",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep12",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/dff8c3a4e2b4c79080.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep12",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeLeaf 3_2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_53 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tncp10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Collapse",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_52 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tncp10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Collapse",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_55_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_51 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_MinusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tncp10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Collapse",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconExpWithChildren.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Empty.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Last.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_LeafIcon.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_50 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCss33803033",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_54_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_53_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss33803033, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:super;white-space:nowrap; ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_52_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss33803033, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:super;white-space:nowrap; ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_51_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss33803033, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:super;white-space:nowrap; ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_50_css {

  private static String[] res = new String[] {
    "org.eclipse.rap.types.CssClass [ .w4tCssc1a24f01, font-size:0px;white-space:nowrap ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss33803033, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:super;white-space:nowrap; ]",
    "org.eclipse.rap.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_55 {

  private static String[] res = new String[] {
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep3",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/bcd0970bc68fbca0.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep3",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 1",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "ddep3",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Click here to simulate drag-drop.",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tnep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Expand",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/82f7c683860a85c182.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 2",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "ddep4",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Click here to simulate drag-drop.",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "tncp10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Collapse",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/a2fb9a01c602ae.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 3",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "ddep10",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Click here to simulate drag-drop.",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep11",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/b0f7e8cebcdea2bd.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep11",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeNode 3_1",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "ddep11",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Click here to simulate drag-drop.",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCssc1a24f01",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep12",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    " ",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/generated/dff8c3a4e2b4c79080.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "waep12",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "TreeLeaf 3_2",
    "\"",
    " />",
    "<",
    "input",
    " ",
    "type",
    "=\"",
    "image",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "name",
    "=\"",
    "ddep12",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    " ",
    "alt",
    "=\"",
    "Click here to simulate drag-drop.",
    "\"",
    " />",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

