/*******************************************************************************
 * Copyright (c) 2002-2006 Innoopract Informationssysteme GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Innoopract Informationssysteme GmbH - initial API and implementation
 ******************************************************************************/
package com.w4t.dhtml.treeviewkit;

import com.w4t.*;
import com.w4t.dhtml.*;
import com.w4t.dhtml.event.DragDropEvent;
import com.w4t.dhtml.event.DragDropListener;
import com.w4t.engine.service.ContextProvider;
import com.w4t.engine.service.IServiceStateInfo;
import com.w4t.event.*;
import com.w4t.util.browser.Default;
import com.w4t.util.browser.Ie5up;
import com.w4t.util.image.ImageCache;

/** <p>Tests the rendering for com.w4t.dhtml.TreeView (and thus for
  * TreeNode and TreeLeaf as well) for Navigator 6up.</p>
  */
public class TreeViewRenderer_Default_Script_Test extends RenderingTestCase {

  public TreeViewRenderer_Default_Script_Test( final String name ) {
    super( name );
    setGenerateResources( false );
  }
  
  protected void setUp() throws Exception {
    super.setUp();
    Fixture.setPrivateField( ImageCache.class, null, "_instance", null );
  }
  
  public void tearDown() throws Exception {
    super.tearDown();
    Fixture.setPrivateField( ImageCache.class, null, "_instance", null );
  }
  
  // testing methods
  //////////////////

  public void testMarkupAppender() throws Exception {
    WebForm form = Fixture.getEmptyWebFormInstance();
    TreeView treeView = new TreeView();
    form.add( treeView, WebBorderLayout.CENTER );
    HtmlResponseWriter outDummy = new HtmlResponseWriter();
    Fixture.fakeBrowser( new Ie5up( true ) );
    ContextProvider.getStateInfo().setResponseWriter( outDummy );
    Fixture.renderComponent( treeView );
    HtmlResponseWriter outExpected = new HtmlResponseWriter();
    ContextProvider.getStateInfo().setResponseWriter( outExpected );
    WebRenderEvent evt;
    evt = new WebRenderEvent( form, WebRenderEvent.AFTER_RENDER );
    evt.processEvent();
    String markup = Fixture.getAllMarkup( outExpected );
    String expected 
      = "<script type=\"text/javascript\">" 
      + "try {document.body.onmouseup = dragDropHandler.clearDragDrop;" 
      + "var jtree=document.getElementById(\"p2\");jtree.style.height=\"0px\";" 
      + "} catch( e ) { }" 
      + "</script>";
    assertEquals( expected, markup );
  }
  
  public void testEncoding() throws Exception {
    // needed 
    WebForm testForm = new WebForm() {    
      protected void setWebComponents() throws Exception {      
      }
    };
    TreeView tv = new TreeView();
    testForm.add( tv, WebBorderLayout.CENTER );
    // node 
    TreeNode node = new TreeNode();
    node.setLabel( "TrööNädü" );
    node.setTitle( "Title of node:öäüß" );
    tv.addItem( node );
    TreeLeaf leaf = new TreeLeaf();
    leaf.setLabel( "ßöäpü" );
    tv.addItem( leaf );
    
    Fixture.fakeBrowser( new Default( true, false ) );
    Fixture.fakeResponseWriter();
    Fixture.renderComponent( tv );
    IServiceStateInfo stateInfo = ContextProvider.getStateInfo();
    String allMarkup = Fixture.getAllMarkup( stateInfo.getResponseWriter() );
    // test markup of node
    String expected 
      = "&nbsp;&nbsp;Tr&ouml;&ouml;N&auml;d&uuml;</span>";
    assertTrue( allMarkup.indexOf( expected ) != -1 );
    // test markup of leaf
    expected 
      = "&nbsp;&nbsp;Tr&ouml;&ouml;N&auml;d&uuml;</span>"; 
    assertTrue( allMarkup.indexOf( expected ) != -1 );
  }
  
  public void testRender() throws Exception {
    // reset the component counter, so that we have always the same IDs
    resetWebComponentCounter();
    // needed 
    WebForm testForm = new WebForm() {    
      protected void setWebComponents() throws Exception {      
      }
    };
    
    TreeView tv = new TreeView();
    testForm.add( tv, WebBorderLayout.CENTER );
    
    // node without children
    TreeNode tn1 = new TreeNode();
    tn1.setLabel( "TreeNode 1" );
    tv.addItem( tn1 );
    
    // node with child nodes
    TreeNode tn2 = new TreeNode();
    tn2.setLabel( "TreeNode 2" );
    tv.addItem( tn2 );

    TreeNode tn2_1 = new TreeNode();
    tn2_1.setLabel( "TreeNode 2_1" );
    tn2.addItem( tn2_1 );
    tn2.addWebActionListener( new WebActionListener() {
      public void webActionPerformed( final WebActionEvent e ) {
      }
    });

    TreeNode tn2_1_1 = new TreeNode();
    tn2_1_1.setLabel( "TreeNode 2_1_1" );
    tn2_1.addItem( tn2_1_1 );

    TreeNode tn2_1_2 = new TreeNode();
    tn2_1_2.setLabel( "TreeNode 2_1_2" );
    tn2_1.addItem( tn2_1_2 );

    TreeLeaf tl2_1_3 = new TreeLeaf();
    tl2_1_3.setLabel( "TreeLeaf 2_1_3" );
    tn2_1.addItem( tl2_1_3 );

    TreeNode tn2_2 = new TreeNode();
    tn2_2.setLabel( "TreeNode 2_2" );
    tn2.addItem( tn2_2 );

    // node with child node and leaf
    TreeNode tn3 = new TreeNode();
    tn3.setLabel( "TreeNode 3" );
    tv.addItem( tn3 );

    TreeNode tn3_1 = new TreeNode();
    tn3_1.setLabel( "TreeNode 3_1" );
    tn3.addItem( tn3_1 );

    TreeLeaf tl3_2 = new TreeLeaf();
    tl3_2.setLabel( "TreeLeaf 3_2" );
    tn3.addItem( tl3_2 );
    
    // needed for renderer loading    
    Fixture.fakeBrowser( new Default( true, false ) );


    // perform actual tests
    ///////////////////////
    doRenderTest( tv, 110 );
    
    // set a single node expanded 
    tn3.setExpanded( true );
    doRenderTest( tv, 111 );
    String[] expectedLibs = new String[] {
      "resources/js/treeview/doubleclick_script.js",
      "resources/js/treeview/treeview_default.js"
    };
    assertJSLibraries( expectedLibs );

    // change image set
    tv.setImageSetName( "resources/images/treeview/swing/Swing" );
    doRenderTest( tv, 112 );
    
    // change back the image set of a single node
    tn2_1.setImageSetName( "resources/images/treeview/modern/Modern" );
    doRenderTest( tv, 113 );
    
    // add webActionEventListener for tree leaf
    tv.addWebActionListener( new WebActionListener() {
      public void webActionPerformed( WebActionEvent e ) {
        // do nothing
      }
    });
    doRenderTest( tv, 114 );
    
    tv.addDragDropListener( new DragDropListener() {
      public void receivedDragDrop( DragDropEvent evt ) {
        // do nothing
      }
    } );
    doRenderTest( tv, 115 );
  }

  private void assertJSLibraries( final String[] expectedLibraries ) {
    IServiceStateInfo stateInfo = ContextProvider.getStateInfo();
    HtmlResponseWriter writer = stateInfo.getResponseWriter();
    String[] libraries = writer.getJSLibraries();
    assertEquals( expectedLibraries.length, libraries.length );
    for( int i = 0; i < libraries.length; i++ ) {
      assertEquals( expectedLibraries[ i ], libraries[ i ] );
    }
  }
  
}
//$endOfPublicClass
class Render_115_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]",
    "com.w4t.types.CssClass [ .w4tCss3b80e8de, font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_115 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_show\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop11\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p3')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p3')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:dragDropHandler.doDragDrop( 'p3' );",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/swing/Swing', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:dragDropHandler.doDragDrop( 'p4' );",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/swing/Swing', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p10')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p10')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:dragDropHandler.doDragDrop( 'p10' );",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p11')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p11')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:dragDropHandler.doDragDrop( 'p11' );",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss3b80e8de",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p12')",
    "\"",
    " ",
    "onmousedown",
    "=\"",
    "eventHandler.suspendSubmit();dragDropHandler.mouseDown( 'p12' )",
    "\"",
    " ",
    "onmouseout",
    "=\"",
    "eventHandler.resumeSubmit();",
    "\"",
    " ",
    "onmouseup",
    "=\"",
    "eventHandler.resumeSubmit();",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "</",
    "span",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p12')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "TreeLeaf 3_2",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:dragDropHandler.doDragDrop( 'p12' );",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/dragDrop.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_114_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]",
    "com.w4t.types.CssClass [ .w4tCss3b80e8de, font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_114 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_show\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop11\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p3')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p3')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/swing/Swing', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/swing/Swing', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p10')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p10')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p11')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p11')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss3b80e8de",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p12')",
    "\"",
    " ",
    "onmousedown",
    "=\"",
    "eventHandler.suspendSubmit();dragDropHandler.mouseDown( 'p12' )",
    "\"",
    " ",
    "onmouseout",
    "=\"",
    "eventHandler.resumeSubmit();",
    "\"",
    " ",
    "onmouseup",
    "=\"",
    "eventHandler.resumeSubmit();",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "</",
    "span",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p12')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "TreeLeaf 3_2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_113 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_show\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop11\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/swing/Swing', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/swing/Swing', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss3b80e8de",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_112 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_show\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop11\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/swing/Swing', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/swing/Swing', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_MinusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconExpWithChildren.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss3b80e8de",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_Last.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/swing/Swing_LeafIcon.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_113_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]",
    "com.w4t.types.CssClass [ .w4tCss3b80e8de, font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_111 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_show\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop11\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/modern/Modern', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/modern/Modern', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_MinusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconExpWithChildren.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:block;font-size: 0px;",
    "\"",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3_1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp11",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "p12",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss3b80e8de",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Empty.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Last.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_LeafIcon.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeLeaf 3_2",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_112_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]",
    "com.w4t.types.CssClass [ .w4tCss3b80e8de, font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_110 {

  private static String[] res = new String[] {
    "<",
    "script",
    " ",
    "type",
    "=\"",
    "text/javascript",
    "\"",
    ">",
    "document.body.onmouseup = dragDropHandler.clearDragDrop;",
    "</",
    "script",
    ">",
    "<",
    "div",
    " ",
    "align",
    "=\"",
    "left",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCss30ca4964",
    "\"",
    ">",
    "",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop3\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop4\" value=\"vis_hide\" /> ",
    "<input type=\"hidden\" name=\"treeNodeToggleStateInfop10\" value=\"vis_hide\" /> ",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_Inner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 1",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp3",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p4', 0, 'resources/images/treeview/modern/Modern', false )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusInner.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop4",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript:eventHandler.webActionPerformed('p4')",
    "\"",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 2",
    "</",
    "a",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp4",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "style",
    "=\"",
    "font-size: 0px;",
    "\"",
    ">",
    "<",
    "a",
    " ",
    "href",
    "=\"",
    "javascript: treeViewHandler.toggle( 'p10', 0, 'resources/images/treeview/modern/Modern', true )",
    "\"",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "togp10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_PlusLast.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "</",
    "a",
    ">",
    "<",
    "img",
    " ",
    "id",
    "=\"",
    "icop10",
    "\"",
    " ",
    "src",
    "=\"",
    "resources/images/treeview/modern/Modern_IconCol.gif",
    "\"",
    " ",
    "border",
    "=\"",
    "0",
    "\"",
    ">",
    "<",
    "span",
    " ",
    "class",
    "=\"",
    "w4tCsse06fabcd",
    "\"",
    " ",
    "title",
    "=\"",
    "",
    "\"",
    ">",
    "&nbsp;",
    "&nbsp;",
    "TreeNode 3",
    "</",
    "span",
    ">",
    "</",
    "div",
    ">",
    "<",
    "div",
    " ",
    "id",
    "=\"",
    "divp10",
    "\"",
    " ",
    "style",
    "=\"",
    "display:none;font-size: 0px;",
    "\"",
    ">",
    "</",
    "div",
    ">",
    "</",
    "div",
    ">"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_111_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]",
    "com.w4t.types.CssClass [ .w4tCss3b80e8de, font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

class Render_110_css {

  private static String[] res = new String[] {
    "com.w4t.types.CssClass [ .w4tCsse06fabcd, font-family:arial,verdana;font-size:8pt;color:#000000;text-decoration:none;vertical-align:top;white-space:nowrap; ]",
    "com.w4t.types.CssClass [ .w4tCss30ca4964, display:block;font-size:0px; ]"
  };

  static String[] getRes() {
    return res;
  }
}

